curr_dir = $(shell pwd)/
all: main

main:
	g++ -std=c++11 main.cpp -o program -I ../../../../VITA_DM/Source/ -L ../../../../VITA_DM/Executables/lib -lCM -lDeM -lDSM -L ../../../../VITA_DM/DM_IoTvity/ -lDM_iotivity -ljson
